// The aimodels.fun directory. Hand-curated snapshot of the AI model
// landscape, last researched July 2026. Opinions are editorial; specifics
// change fast — the "asOf" date is shown throughout the UI.

export const AS_OF = "July 2026";

export type Category = "chat" | "open" | "image" | "video" | "audio";

export const CATEGORIES: { id: Category; label: string; emoji: string; blurb: string }[] = [
  { id: "chat", label: "Chat & work", emoji: "💬", blurb: "Frontier assistants for thinking, writing, coding, and agents." },
  { id: "open", label: "Open weights", emoji: "🔓", blurb: "Download the weights, run it yourself, own your stack." },
  { id: "image", label: "Images", emoji: "🎨", blurb: "Text-to-image for art, product shots, and design." },
  { id: "video", label: "Video", emoji: "🎬", blurb: "Text- and image-to-video generation." },
  { id: "audio", label: "Audio & voice", emoji: "🎙️", blurb: "Speech, voices, and music." },
];

export type Model = {
  slug: string;
  name: string;
  maker: string;
  category: Category;
  tagline: string;
  vibe: string; // one playful line
  strengths: string[];
  weaknesses: string[];
  bestFor: string[];
  pricing: string;
  openWeights: boolean;
  access: string; // where/how you use it
  status?: "hot" | "new" | "deprecated";
  notes?: string;
};

export const MODELS: Model[] = [
  // ---- Chat & work (closed frontier) ----
  {
    slug: "claude-fable-5",
    name: "Claude Fable 5",
    maker: "Anthropic",
    category: "chat",
    tagline: "The new frontier tier — strongest coding model you can actually use.",
    vibe: "The overachiever who also reads philosophy.",
    strengths: [
      "Top of SWE-Bench Pro (~80%) — best-in-class real-world coding",
      "First of Anthropic's Mythos-class tier; excels at long agentic tasks",
      "Careful, honest reasoning style",
    ],
    weaknesses: ["Premium pricing", "Overkill for simple chat tasks"],
    bestFor: ["Serious coding & agents", "Hard reasoning", "High-stakes work"],
    pricing: "Premium API / paid plans",
    openWeights: false,
    access: "Claude apps, API",
    status: "hot",
  },
  {
    slug: "claude-opus-4-8",
    name: "Claude Opus 4.8",
    maker: "Anthropic",
    category: "chat",
    tagline: "The everyday-value frontier pick for coding and agents.",
    vibe: "The reliable senior engineer on your team.",
    strengths: [
      "Near-Fable coding ability at a friendlier price",
      "Excellent at agentic workflows and long documents",
      "Great instruction-following and tone",
    ],
    weaknesses: ["Not the absolute benchmark leader anymore", "Slower than small models"],
    bestFor: ["Daily coding", "Agents & automation", "Writing that matters"],
    pricing: "Mid-tier API / paid plans",
    openWeights: false,
    access: "Claude apps, API",
    status: "hot",
  },
  {
    slug: "claude-sonnet-5",
    name: "Claude Sonnet 5",
    maker: "Anthropic",
    category: "chat",
    tagline: "Fast, balanced, and cheap enough to ship in products.",
    vibe: "The quick-witted generalist.",
    strengths: ["Strong quality-per-rupee", "Fast responses", "Good coding for the price"],
    weaknesses: ["Frontier models beat it on the hardest problems"],
    bestFor: ["Product integrations", "High-volume assistants", "Everyday chat"],
    pricing: "Affordable API",
    openWeights: false,
    access: "Claude apps, API",
  },
  {
    slug: "claude-haiku-4-5",
    name: "Claude Haiku 4.5",
    maker: "Anthropic",
    category: "chat",
    tagline: "Tiny price, surprising brains — the volume workhorse.",
    vibe: "Small, caffeinated, everywhere at once.",
    strengths: ["Very cheap and very fast", "Great for classification, extraction, routing"],
    weaknesses: ["Struggles with genuinely hard reasoning"],
    bestFor: ["High-volume pipelines", "Latency-sensitive apps", "Cost control"],
    pricing: "Budget API",
    openWeights: false,
    access: "API",
  },
  {
    slug: "gpt-5-6",
    name: "GPT-5.6",
    maker: "OpenAI",
    category: "chat",
    tagline: "ChatGPT's default brain since July 9, 2026.",
    vibe: "The polished all-rounder everyone's already met.",
    strengths: [
      "Excellent general assistant — writing, tool use, everyday questions",
      "Huge ecosystem and app integrations",
      "Strong multimodal understanding",
    ],
    weaknesses: ["Trails Claude on hard real-world coding benchmarks"],
    bestFor: ["General assistance", "Consumer use", "Tool-using workflows"],
    pricing: "Free tier + paid plans / API",
    openWeights: false,
    access: "ChatGPT, API",
    status: "new",
  },
  {
    slug: "gpt-5-5",
    name: "GPT-5.5",
    maker: "OpenAI",
    category: "chat",
    tagline: "The price-performance sweet spot of the GPT-5 family.",
    vibe: "Last month's flagship, this month's bargain.",
    strengths: ["Great writing and tool use per dollar", "Battle-tested in production"],
    weaknesses: ["Superseded by 5.6 as the default"],
    bestFor: ["Cost-aware products", "Writing at scale"],
    pricing: "Mid-tier API",
    openWeights: false,
    access: "API",
  },
  {
    slug: "gemini-3-pro",
    name: "Gemini 3 Pro",
    maker: "Google",
    category: "chat",
    tagline: "Long context, deep Google integration, serious multimodal chops.",
    vibe: "The one with access to the world's biggest library.",
    strengths: [
      "Massive context windows for huge documents and codebases",
      "Native multimodal (video/audio/image understanding)",
      "Workspace & Android integration",
    ],
    weaknesses: ["Assistant personality can feel corporate"],
    bestFor: ["Long-document work", "Multimodal analysis", "Google-shop teams"],
    pricing: "Free tier + paid plans / API",
    openWeights: false,
    access: "Gemini app, AI Studio, Vertex",
  },
  {
    slug: "grok-4",
    name: "Grok 4",
    maker: "xAI",
    category: "chat",
    tagline: "Frontier reasoning with a live feed of X and an attitude.",
    vibe: "The loud one at the party who's oddly good at math.",
    strengths: ["Strong reasoning benchmarks", "Real-time X/Twitter data", "Distinct personality"],
    weaknesses: ["Personality is polarizing", "Smaller ecosystem than rivals"],
    bestFor: ["Real-time trends & news", "Users already on X"],
    pricing: "Paid plans / API",
    openWeights: false,
    access: "X, Grok apps, API",
  },
  // ---- Open weights ----
  {
    slug: "llama-4",
    name: "Llama 4 (Scout & Maverick)",
    maker: "Meta",
    category: "open",
    tagline: "The most-deployed open family on the planet.",
    vibe: "The people's champion.",
    strengths: [
      "Best-known open family with a giant tooling ecosystem",
      "Scout is efficient; Maverick pushes quality",
      "Runs everywhere — from laptops to clusters",
    ],
    weaknesses: ["License has strings for the largest deployers", "Frontier closed models still lead on hard tasks"],
    bestFor: ["Self-hosting", "Fine-tuning", "Privacy-sensitive apps"],
    pricing: "Open weights (free) — you pay for compute",
    openWeights: true,
    access: "Hugging Face, llama.com, cloud hosts",
    status: "hot",
  },
  {
    slug: "deepseek",
    name: "DeepSeek V3 / R1",
    maker: "DeepSeek",
    category: "open",
    tagline: "Frontier-adjacent reasoning at open-weight prices.",
    vibe: "The scholarship kid who topped the exam.",
    strengths: [
      "R1-style reasoning traces at a fraction of frontier cost",
      "Genuinely competitive benchmarks, open weights",
      "Very cheap hosted API",
    ],
    weaknesses: ["Hosted service raises data-residency questions for some teams"],
    bestFor: ["Reasoning on a budget", "Self-hosted thinking models"],
    pricing: "Open weights + very cheap API",
    openWeights: true,
    access: "Hugging Face, DeepSeek API",
  },
  {
    slug: "glm-5",
    name: "GLM-5 family",
    maker: "Z.AI (Zhipu)",
    category: "open",
    tagline: "A top open-weight contender pushing the frontier from China.",
    vibe: "The fast riser everyone underestimated.",
    strengths: ["Among the strongest open-weight results in 2026", "Good coding and agent skills"],
    weaknesses: ["Smaller Western tooling ecosystem than Llama"],
    bestFor: ["Open-weight frontier chasers", "Multilingual products"],
    pricing: "Open weights + hosted API",
    openWeights: true,
    access: "Hugging Face, Z.AI API",
    status: "new",
  },
  {
    slug: "qwen-3",
    name: "Qwen 3 family",
    maker: "Alibaba",
    category: "open",
    tagline: "The multilingual open-weight workhorse in every size.",
    vibe: "Speaks more languages than your group chat.",
    strengths: ["Excellent multilingual coverage", "Sizes from tiny to huge", "Strong coding variants"],
    weaknesses: ["Naming/versioning can be confusing"],
    bestFor: ["Non-English products", "Right-sized self-hosting"],
    pricing: "Open weights + hosted API",
    openWeights: true,
    access: "Hugging Face, ModelScope",
  },
  {
    slug: "mistral",
    name: "Mistral (Large & open models)",
    maker: "Mistral AI",
    category: "open",
    tagline: "Europe's efficiency specialists — small models that punch up.",
    vibe: "Minimalist, sharp, slightly French about it.",
    strengths: ["Great efficiency per parameter", "EU data-residency story", "Solid open releases"],
    weaknesses: ["Flagships trail the biggest frontier models"],
    bestFor: ["EU compliance needs", "Edge & efficient serving"],
    pricing: "Open weights + API / paid plans",
    openWeights: true,
    access: "Hugging Face, La Plateforme, Le Chat",
  },
  // ---- Images ----
  {
    slug: "midjourney-v8",
    name: "Midjourney V8.1",
    maker: "Midjourney",
    category: "image",
    tagline: "Still the king of aesthetics.",
    vibe: "The art-school prodigy.",
    strengths: ["Unmatched artistic quality and style range", "Strong community and remix culture"],
    weaknesses: ["Less literal about complex instructions", "No open weights; subscription only"],
    bestFor: ["Art & concept work", "Moodboards", "Anything that must look gorgeous"],
    pricing: "Subscription",
    openWeights: false,
    access: "Web app, Discord",
    status: "hot",
  },
  {
    slug: "flux",
    name: "FLUX.1 / FLUX.2",
    maker: "Black Forest Labs",
    category: "image",
    tagline: "The open-source photorealism (and typography!) champion.",
    vibe: "The indie darling that outshoots the studios.",
    strengths: [
      "Best open-weights image quality; text/typography actually works",
      "klein variants are very fast",
      "Self-host or use hosted APIs",
    ],
    weaknesses: ["Top variants need real GPUs to self-host"],
    bestFor: ["Open-source pipelines", "Product images with text", "Fine-tuned styles"],
    pricing: "Open weights + hosted APIs",
    openWeights: true,
    access: "Hugging Face, fal, Replicate",
    status: "hot",
  },
  {
    slug: "gpt-image-2",
    name: "GPT Image 2",
    maker: "OpenAI",
    category: "image",
    tagline: "The instruction-following champion — it draws what you meant.",
    vibe: "The literal-minded perfectionist.",
    strengths: ["Best at complex, precise instructions", "Great in-context editing", "Easy via ChatGPT/API"],
    weaknesses: ["Aesthetics can feel safer than Midjourney's"],
    bestFor: ["Precise compositions", "Edits & iterations", "Diagrams-meets-art"],
    pricing: "ChatGPT plans / API",
    openWeights: false,
    access: "ChatGPT, API",
  },
  {
    slug: "recraft-v3",
    name: "Recraft V3",
    maker: "Recraft",
    category: "image",
    tagline: "Design-native generation — vectors, brand styles, speed.",
    vibe: "The design agency in an API.",
    strengths: ["SVG/vector output", "Brand-style control", "Fast"],
    weaknesses: ["Less general-purpose than the big names"],
    bestFor: ["Logos & icons", "Brand assets", "UI illustration"],
    pricing: "Freemium + API",
    openWeights: false,
    access: "Web app, API",
  },
  // ---- Video ----
  {
    slug: "veo-3-1",
    name: "Veo 3.1",
    maker: "Google",
    category: "video",
    tagline: "The most capable video model — cinematic, consistent, obedient.",
    vibe: "The blockbuster director.",
    strengths: [
      "Best temporal consistency and instruction-following",
      "Film-like camera behavior",
      "Native audio generation",
    ],
    weaknesses: ["Premium pricing", "Access gated through Google products"],
    bestFor: ["Cinematic shots", "Ads & trailers", "Complex scene direction"],
    pricing: "Paid (Gemini/Flow, API)",
    openWeights: false,
    access: "Gemini, Flow, Vertex API",
    status: "hot",
  },
  {
    slug: "seedance-2",
    name: "Seedance 2.x",
    maker: "ByteDance",
    category: "video",
    tagline: "The hottest image-to-video model, especially for longer clips.",
    vibe: "The TikTok-native auteur.",
    strengths: ["Top of video leaderboards in 2026", "Strong long-form image-to-video", "Great motion quality"],
    weaknesses: ["Ecosystem/access less unified in the West"],
    bestFor: ["Image-to-video", "Longer clips", "Social content"],
    pricing: "Hosted platforms / API",
    openWeights: false,
    access: "Partner platforms, API",
    status: "new",
  },
  {
    slug: "kling-3-turbo",
    name: "Kling 3.0 Turbo",
    maker: "Kuaishou",
    category: "video",
    tagline: "The strongest value pick in AI video.",
    vibe: "The scrappy studio that ships fast.",
    strengths: ["Great quality-per-cost", "Fast generations", "Solid image-to-video"],
    weaknesses: ["Top-end quality trails Veo/Seedance"],
    bestFor: ["Volume video content", "Budget-conscious creators"],
    pricing: "Freemium + credits",
    openWeights: false,
    access: "Kling app, API",
  },
  {
    slug: "sora-2",
    name: "Sora 2",
    maker: "OpenAI",
    category: "video",
    tagline: "The pioneer — now riding into the sunset.",
    vibe: "The retired rockstar.",
    strengths: ["Sparked the AI-video era", "Strong physical realism for its time"],
    weaknesses: ["Deprecated April 2026; API shutdown scheduled September 24, 2026"],
    bestFor: ["Nothing new — migrate to Veo/Seedance/Kling"],
    pricing: "—",
    openWeights: false,
    access: "Sunsetting",
    status: "deprecated",
  },
  // ---- Audio ----
  {
    slug: "elevenlabs",
    name: "ElevenLabs",
    maker: "ElevenLabs",
    category: "audio",
    tagline: "The default choice for lifelike AI voices.",
    vibe: "The voice actor with a thousand faces.",
    strengths: ["Extremely natural TTS and voice cloning", "Dubbing across languages", "Real-time agents"],
    weaknesses: ["Costs add up at scale", "Cloning ethics require care and consent"],
    bestFor: ["Voiceovers", "Audiobooks & dubbing", "Voice agents"],
    pricing: "Freemium + subscription/API",
    openWeights: false,
    access: "Web app, API",
    status: "hot",
  },
  {
    slug: "suno",
    name: "Suno",
    maker: "Suno",
    category: "audio",
    tagline: "Full songs — vocals, lyrics, production — from a prompt.",
    vibe: "The garage band that lives in your browser.",
    strengths: ["Complete songs with convincing vocals", "Fast and fun to iterate"],
    weaknesses: ["Fine control is limited", "Industry licensing questions still evolving"],
    bestFor: ["Jingles & demos", "Content soundtracks", "Fun"],
    pricing: "Freemium + subscription",
    openWeights: false,
    access: "Web app",
  },
];

export function modelBySlug(slug: string): Model | undefined {
  return MODELS.find((m) => m.slug === slug);
}

export function categoryLabel(id: Category): string {
  return CATEGORIES.find((c) => c.id === id)?.label ?? id;
}

export function categoryEmoji(id: Category): string {
  return CATEGORIES.find((c) => c.id === id)?.emoji ?? "🤖";
}

export const CATEGORY_COLORS: Record<Category, string> = {
  chat: "var(--violet)",
  open: "var(--green)",
  image: "var(--pink)",
  video: "var(--orange)",
  audio: "var(--blue)",
};
